pipeline {
  agent any

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  environment {
    ARTIFACT_ID = "elbuo8/webapp:${env.BUILD_NUMBER}"
  }

  stages {
    stage('Build') {
      steps {
        sh "Runing building"
      }
    }
    stage('Run tests') {
      steps {
        sh "runnig testing"
      }
    }
  }
}

